In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_pickle('../dados_meteorologicos/T_06216072017.csv')

# Preparando os dados

## Alvos: Iraja, alto da boa vista, copacaba

In [33]:
temp1 = df.drop(['alto_da_boa_vista','iraja','f_copacabana'],axis=1)
temp2 = df.drop(['alto_da_boa_vista','iraja','f_copacabana'],axis=1)
temp3 = df.drop(['alto_da_boa_vista','iraja','f_copacabana'],axis=1)

## Iajá indice topograficos 

alt:12.86
aspect : 288.43
slope: 0.48



In [4]:
temp1['altitude']= np.full((len(temp1)),12.86)
temp1['m_feat']= np.full((len(temp1)),288.43)
temp1['slope']= np.full((len(temp1)),0.48)
temp1['y_var']= df.iraja

In [34]:
temp1.loc['2017-07-28']

riocentro  guaratiba  jardim_botanico  santa_cruz  \
data                                                                     
2017-07-28 00:00:00     19.900        NaN           17.050      18.225   
2017-07-28 01:00:00     20.100        NaN           18.350      16.925   
2017-07-28 02:00:00     19.775        NaN           18.825      16.300   
2017-07-28 03:00:00     19.750        NaN           18.575      15.925   
2017-07-28 04:00:00     19.575        NaN           17.550      15.625   
2017-07-28 05:00:00     18.950        NaN           17.125      15.625   
2017-07-28 06:00:00     17.975        NaN           17.975      15.400   
2017-07-28 07:00:00     18.350        NaN           19.875      16.525   
2017-07-28 08:00:00     20.825        NaN           21.900      20.100   
2017-07-28 09:00:00     24.025        NaN           22.725      22.800   
2017-07-28 10:00:00     25.125        NaN           23.300      24.275   
2017-07-28 11:00:00     24.775        NaN           23.575      25.300   
2017-07-28 12:00:00     24.700        NaN           23.675      26.575   
2017-07-28 13:00:00     25.250        NaN           23.275      26.900   
2017-07-28 14:00:00     25.050        NaN           23.175      26.950   
2017-07-28 15:00:00     25.800        NaN           22.550      25.875   
2017-07-28 16:00:00     24.525        NaN           22.025      24.650   
2017-07-28 17:00:00     22.750        NaN           21.325      22.750   
2017-07-28 18:00:00     21.400        NaN           20.900      21.650   
2017-07-28 19:00:00     21.150        NaN           20.775      20.800   
2017-07-28 20:00:00     20.525        NaN           20.250      19.725   
2017-07-28 21:00:00     19.775        NaN           19.400      19.775   
2017-07-28 22:00:00     21.250        NaN           20.175      19.075   
2017-07-28 23:00:00     21.025        NaN           19.050      18.750   

                     sao_cristovao  marambaia  xerem  ecologia  
data                                                            
2017-07-28 00:00:00         20.625      20.40  14.70     18.25  
2017-07-28 01:00:00         20.275      20.00  14.05     18.25  
2017-07-28 02:00:00         19.650      19.65  13.55     17.15  
2017-07-28 03:00:00         19.650      18.75  13.20     16.00  
2017-07-28 04:00:00         19.175      17.70  12.85     14.65  
2017-07-28 05:00:00         18.850      18.35  12.50     14.75  
2017-07-28 06:00:00         18.475      16.90  12.15     14.40  
2017-07-28 07:00:00         19.800      14.90  11.65     14.45  
2017-07-28 08:00:00         21.475      14.95  11.65     14.45  
2017-07-28 09:00:00         22.200      13.80  11.20     13.90  
2017-07-28 10:00:00         22.825      14.10  11.30     13.30  
2017-07-28 11:00:00         24.575      16.30  12.90     15.50  
2017-07-28 12:00:00         23.825      19.55  16.55     19.10  
2017-07-28 13:00:00         23.700      21.90  19.90     21.75  
2017-07-28 14:00:00         23.025      21.35  21.40     23.40  
2017-07-28 15:00:00         23.050      21.50  23.00     25.10  
2017-07-28 16:00:00         22.775      21.95  23.65     25.85  
2017-07-28 17:00:00         22.025      22.80  23.80     25.90  
2017-07-28 18:00:00         21.250      22.85  24.15     25.95  
2017-07-28 19:00:00         21.050      22.25  24.80     25.85  
2017-07-28 20:00:00         20.975      21.55  23.20     24.60  
2017-07-28 21:00:00         21.200      20.55  19.35     21.85  
2017-07-28 22:00:00         21.325      20.15  16.50     20.30  
2017-07-28 23:00:00         21.000      19.95  15.55     19.40

In [13]:
temp1.head()

riocentro  guaratiba  jardim_botanico  santa_cruz  \
data                                                                     
2016-06-01 00:00:00     25.125     22.350        24.475000      25.125   
2016-06-01 01:00:00     24.975     22.725        24.025000      24.800   
2016-06-01 02:00:00     24.975     23.225        23.925000      24.200   
2016-06-01 03:00:00     24.900     21.600        24.500000      24.200   
2016-06-01 04:00:00     24.700     21.000        23.533333      23.400   

                     sao_cristovao  marambaia  xerem  ecologia  altitude  \
data                                                                       
2016-06-01 00:00:00      25.025000      21.60  19.05      20.8     12.86   
2016-06-01 01:00:00      24.950000      21.20  18.50      20.6     12.86   
2016-06-01 02:00:00      24.800000      20.55  18.25      20.3     12.86   
2016-06-01 03:00:00      24.800000      19.75  18.10      19.6     12.86   
2016-06-01 04:00:00      24.166667      19.70  17.90      19.3     12.86   

                     m_feat  slope      y_var  
data                                           
2016-06-01 00:00:00       1   0.48  24.800000  
2016-06-01 01:00:00       1   0.48  24.550000  
2016-06-01 02:00:00       1   0.48  24.500000  
2016-06-01 03:00:00       1   0.48  24.500000  
2016-06-01 04:00:00       1   0.48  24.133333

## alto da boa vista 
357.63 , 156.79, 5.49


In [5]:
temp2['altitude']= np.full((len(temp2)),357.63)
temp2['m_feat']= np.full((len(temp2)),156.79 )
temp2['slope']= np.full((len(temp2)),5.49)
temp2['y_var']= df.alto_da_boa_vista

## copacabana
15.74, 288.43, 0.96

In [6]:
temp3['altitude']= np.full((len(temp3)),15.74)
temp3['m_feat']= np.full((len(temp3)),288.43 )
temp3['slope']= np.full((len(temp3)),0.96)
temp3['y_var']= df.alto_da_boa_vista

## conjunto principal

In [7]:
temp1 = temp1.reset_index().drop(['data'],axis=1)
temp2 = temp2.reset_index().drop(['data'],axis=1)
temp3 = temp3.reset_index().drop(['data'],axis=1)

In [8]:
dados = pd.concat([temp1,temp2,temp3],axis=0)

In [9]:
dados = dados.drop(['guaratiba'],axis=1)


In [10]:
#tirando nodata
dados = dados.fillna(method='backfill')

# Aplicando os algoritmos de ML

In [11]:
#separando variáveis
y = dados.iloc[:,10].values
x = dados.iloc[:,:10].values


In [12]:
#padronizando os dados 
from sklearn.preprocessing import StandardScaler

In [13]:
Stander = StandardScaler()

In [14]:
x=Stander.fit(x).transform(x)

In [15]:
len(y)

30672

In [16]:
30672*0.75

23004.0

In [17]:
y_train = y[:23004]
y_test = y[23004:]
X_train = x[:23004]
X_test = x[23004:]

# Testando os algoritmos

In [18]:
# importando bibliotecas
from sklearn.metrics import mean_squared_error
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.multioutput import MultiOutputRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR, SVC
from sklearn.neural_network import MLPRegressor



In [74]:
# plota grafico de dispersao e linha de tendencia para o modelo
def plot_show(X_test,y_test,previsao,title,name):
    #plt.figure(figsize=(5,5))
    z= np.polyfit(y_test.flatten(),previsao.flatten(),1)
    p=np.poly1d(z)
    plt.scatter(y_test,previsao,color='k',marker='+')
    plt.title(title)
    plt.plot(y_test,p(y_test),'r--')
    plt.show()
    print('RMSE for ',name,' is ',y_mse[name])
    print('R**2 ',name,' is ',y_r2[name])

In [75]:
# plota grafico de dispersao e linha de tendencia para o modelo
def plot_l(y_test,previsao):
    #plt.figure(figsize=(5,5))
    z= np.polyfit(y_test.flatten(),previsao.flatten(),1)
    p=np.poly1d(z)
    return p

In [19]:
# cria dicionario com os algorimos utilizados 
ESTIMATORS = {    
    "K-nn": KNeighborsRegressor(),                        
    "RandomForestRegressor": RandomForestRegressor(max_depth=50, random_state=2),
    "Decision Tree Regressor":DecisionTreeRegressor(max_depth=5),
    "SVC":SVR(),
    #"NeuralNetwork": MLPRegressor(solver='adam', random_state=1,
     #                             hidden_layer_sizes=(4,4,4,2)),
    "GBR" :GradientBoostingRegressor(n_estimators=35),
    "AdaB" :AdaBoostRegressor(n_estimators=5)
}

In [20]:
#estimador = DecisionTreeRegressor()
estimador = KNeighborsRegressor()

In [21]:
estimador.fit(X_train,y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=None, n_neighbors=5, p=2,
          weights='uniform')

In [22]:
previsao = estimador.predict(X_test)

In [23]:
print(mean_squared_error(y_test,previsao))
print(estimador.score(X_test,y_test))

10.925574095809424
0.4390199541154987


In [24]:
# aplicando os algortimos
y_test_predict = dict()
y_mse = dict()
y_r2 = dict()
#fig = plt.figure(figsize=(15,10))
i=1
for name, estimator in ESTIMATORS.items():    
    estimator.fit(X_train, y_train)                    # fit() with instantiated object
    y_test_predict[name] = previsao = estimator.predict(X_test)   # Make predictions and save it in dict under key: name
    y_mse[name] = mean_squared_error(y_test, estimator.predict(X_test))
    y_r2[name] = estimator.score(X_test,y_test)
    
    #grafico
#     z= np.polyfit(y_test.flatten(),previsao.flatten(),1)
#     p=np.poly1d(z)
#     ax=fig.add_subplot(2,3,i)
#     ax.scatter(y_test,previsao,color='k',marker='+')
#     ax.set_xlabel('Observado')
#     ax.set_ylabel('Estimado')
#     ax.set_title(name)
#     ax.plot(y_test,p(y_test),'r--')
#     i+=1

# plt.tight_layout()
# #plt.savefig('../../../Qualificacao/MML_evaporacao_INMET.png')
# plt.show()

    

R=pd.DataFrame({'mse':list(y_mse.values()),    # Padronizando o os dois
                 'R2':list(y_r2.values())}, 
                index=list(y_r2.keys()))

/home/pensario/.local/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/pensario/.local/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [25]:
R

mse        R2
K-nn                     10.925574  0.439020
RandomForestRegressor     0.182630  0.990623
Decision Tree Regressor   1.589724  0.918375
SVC                       3.085551  0.841571
GBR                       1.129124  0.942024
AdaB                      2.335729  0.880071

# Teste 

In [186]:
x[1]

array([ 0.0880346 ,  0.04097513,  0.05672916,  0.03672865, -0.45679216,
       -0.62646686, -0.57054586, -0.71598516, -0.70710678, -0.81076696])

In [188]:
estimador.predict([x[1]])

array([24.4985])

In [189]:
Stander.inverse_transform(x[1])

array([24.975, 24.025, 24.8  , 24.95 , 21.2  , 18.5  , 20.6  , 12.86 ,
        1.   ,  0.48 ])

In [190]:
dados.head()

riocentro  jardim_botanico  santa_cruz  sao_cristovao  marambaia  xerem  \
0     25.125        24.475000      25.125      25.025000      21.60  19.05   
1     24.975        24.025000      24.800      24.950000      21.20  18.50   
2     24.975        23.925000      24.200      24.800000      20.55  18.25   
3     24.900        24.500000      24.200      24.800000      19.75  18.10   
4     24.700        23.533333      23.400      24.166667      19.70  17.90   

   ecologia  altitude  m_feat  slope      y_var  
0      20.8     12.86     1.0   0.48  24.800000  
1      20.6     12.86     1.0   0.48  24.550000  
2      20.3     12.86     1.0   0.48  24.500000  
3      19.6     12.86     1.0   0.48  24.500000  
4      19.3     12.86     1.0   0.48  24.133333

In [191]:
df.head()

riocentro  alto_da_boa_vista  guaratiba      iraja  \
data                                                                      
2016-06-01 00:00:00     25.125          21.000000     22.350  24.800000   
2016-06-01 01:00:00     24.975          21.000000     22.725  24.550000   
2016-06-01 02:00:00     24.975          20.950000     23.225  24.500000   
2016-06-01 03:00:00     24.900          21.000000     21.600  24.500000   
2016-06-01 04:00:00     24.700          20.166667     21.000  24.133333   

                     jardim_botanico  santa_cruz  sao_cristovao  marambaia  \
data                                                                         
2016-06-01 00:00:00        24.475000      25.125      25.025000      21.60   
2016-06-01 01:00:00        24.025000      24.800      24.950000      21.20   
2016-06-01 02:00:00        23.925000      24.200      24.800000      20.55   
2016-06-01 03:00:00        24.500000      24.200      24.800000      19.75   
2016-06-01 04:00:00        23.533333      23.400      24.166667      19.70   

                     xerem  f_copacabana  ecologia  
data                                                
2016-06-01 00:00:00  19.05         22.90      20.8  
2016-06-01 01:00:00  18.50         22.80      20.6  
2016-06-01 02:00:00  18.25         23.10      20.3  
2016-06-01 03:00:00  18.10         23.15      19.6  
2016-06-01 04:00:00  17.90         22.70      19.3

In [192]:
x_guaratiba = np.array([24.975, 24.025, 24.8  , 24.95 ,
                        21.2  , 18.5  , 20.6  , 
                        5.83 , 1., 0.11 ])

In [194]:
x_guaratiba = Stander.transform([x_guaratiba])

In [195]:
x_guaratiba

array([[ 0.0880346 ,  0.04097513,  0.05672916,  0.03672865, -0.45679216,
        -0.62646686, -0.57054586, -0.75942002, -0.70710678, -0.97469252]])

In [196]:
x_guaratiba[0]

array([ 0.0880346 ,  0.04097513,  0.05672916,  0.03672865, -0.45679216,
       -0.62646686, -0.57054586, -0.75942002, -0.70710678, -0.97469252])

In [198]:
estimador.predict([x_guaratiba[0]])

array([24.4985])

# Exportando dados e modelos

In [26]:
# conjunto treinamento
dados.to_csv('../dados_meteorologicos/conjunto_trein_val_062016_072017.csv')

In [27]:
knn = KNeighborsRegressor()                        
RF = RandomForestRegressor(max_depth=50, random_state=2)
DT = DecisionTreeRegressor(max_depth=5)
SVR_pred = SVR()
GBR = GradientBoostingRegressor(n_estimators=35)
AdaB = AdaBoostRegressor(n_estimators=5)

In [28]:
knn.fit(X_train,y_train)
RF.fit(X_train,y_train)
DT.fit(X_train,y_train)
SVR_pred.fit(X_train,y_train)
GBR.fit(X_train,y_train)
AdaB.fit(X_train,y_train)

/home/pensario/.local/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/pensario/.local/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


AdaBoostRegressor(base_estimator=None, learning_rate=1.0, loss='linear',
         n_estimators=5, random_state=None)

In [29]:
from sklearn.externals import joblib

In [30]:
joblib.dump(AdaB,'../modelos/AdaB.pk') #AdaBoostRegressor
joblib.dump(RF,'../modelos/RF.pk') #Random forest
joblib.dump(DT,'../modelos/DT.pk') #arvore de decisao
joblib.dump(SVR_pred,'../modelos/SVR.pk') #vetor suporte
joblib.dump(GBR,'../modelos/GBR.pk') #gradiente de boosting



['../modelos/GBR.pk']

In [222]:
joblib.dump(Stander,'../modelos/transform_dados.pk')

['../modelos/transform_dados.pk']

array([24.4985])

In [223]:
transform = joblib.load('../modelos/transform_dados.pk')